import os
from glob import glob
import torch
import pandas as pd

if __name__ == '__main__':

    data_models = [
        "allenai-Olmo-3-1025-7B.pth",
        "allenai-Olmo-3-1125-32B.pth",
        "allenai-Olmo-3.1-32B-Instruct.pth",
        "allenai-Olmo-3.1-32B-Think.pth",
        "allenai-Olmo-3-7B-Instruct.pth",
        "allenai-Olmo-3-7B-Think.pth",
        "deepseek-ai-DeepSeek-R1-Distill-Llama-70B.pth",
        "deepseek-ai-DeepSeek-R1-Distill-Llama-8B.pth",
        "deepseek-ai-DeepSeek-R1-Distill-Qwen-14B.pth",
        "deepseek-ai-DeepSeek-R1-Distill-Qwen-1.5B.pth",
        "deepseek-ai-DeepSeek-R1-Distill-Qwen-32B.pth",
        "deepseek-ai-DeepSeek-R1-Distill-Qwen-7B.pth",
        "meta-llama-Llama-3.1-70B-Instruct.pth",
        "meta-llama-Llama-3.1-70B.pth",
        "meta-llama-Llama-3.1-8B-Instruct.pth",
        "meta-llama-Llama-3.1-8B.pth",
        "meta-llama-Llama-3.2-1B-Instruct.pth",
        "meta-llama-Llama-3.2-1B.pth",
        "meta-llama-Llama-3.2-3B-Instruct.pth",
        "meta-llama-Llama-3.2-3B.pth",
        "meta-llama-Meta-Llama-3-8B-Instruct.pth",
        "meta-llama-Meta-Llama-3-8B.pth",
        "Qwen-Qwen1.5-0.5B-Chat.pth",
        "Qwen-Qwen1.5-0.5B.pth",
        "Qwen-Qwen1.5-14B-Chat.pth",
        "Qwen-Qwen1.5-14B.pth",
        "Qwen-Qwen1.5-1.8B-Chat.pth",
        "Qwen-Qwen1.5-1.8B.pth",
        "Qwen-Qwen1.5-32B-Chat.pth",
        "Qwen-Qwen1.5-32B.pth",
        "Qwen-Qwen1.5-4B-Chat.pth",
        "Qwen-Qwen1.5-4B.pth",
        "Qwen-Qwen1.5-72B-Chat.pth",
        "Qwen-Qwen1.5-72B.pth",
        "Qwen-Qwen1.5-7B-Chat.pth",
        "Qwen-Qwen1.5-7B.pth",
        "Qwen-Qwen2-0.5B-Instruct.pth",
        "Qwen-Qwen2-0.5B.pth",
        "Qwen-Qwen2-1.5B-Instruct.pth",
        "Qwen-Qwen2-1.5B.pth",
        "Qwen-Qwen2-72B-Instruct.pth",
        "Qwen-Qwen2-72B.pth",
        "Qwen-Qwen2-7B-Instruct.pth",
        "Qwen-Qwen2-7B.pth",
        "Qwen-Qwen2.5-0.5B-Instruct.pth",
        "Qwen-Qwen2.5-0.5B.pth",
        "Qwen-Qwen2.5-14B-Instruct.pth",
        "Qwen-Qwen2.5-14B.pth",
        "Qwen-Qwen2.5-1.5B-Instruct.pth",
        "Qwen-Qwen2.5-1.5B.pth",
        "Qwen-Qwen2.5-32B-Instruct.pth",
        "Qwen-Qwen2.5-32B.pth",
        "Qwen-Qwen2.5-3B-Instruct.pth",
        "Qwen-Qwen2.5-3B.pth",
        "Qwen-Qwen2.5-72B-Instruct.pth",
        "Qwen-Qwen2.5-72B.pth",
        "Qwen-Qwen2.5-7B-Instruct.pth",
        "Qwen-Qwen2.5-7B.pth",
        "Qwen-Qwen2.5-Coder-0.5B.pth",
        "Qwen-Qwen2.5-Coder-14B.pth",
        "Qwen-Qwen2.5-Coder-1.5B.pth",
        "Qwen-Qwen2.5-Coder-32B.pth",
        "Qwen-Qwen2.5-Coder-3B.pth",
        "Qwen-Qwen2.5-Coder-7B.pth",
        "Qwen-Qwen2.5-Math-1.5B.pth",
        "Qwen-Qwen2.5-Math-72B.pth",
        "Qwen-Qwen2.5-Math-7B.pth",
        "Qwen-Qwen2.5-VL-32B-Instruct.pth",
        "Qwen-Qwen2.5-VL-3B-Instruct.pth",
        "Qwen-Qwen2.5-VL-72B-Instruct.pth",
        "Qwen-Qwen2.5-VL-7B-Instruct.pth",
        "Qwen-Qwen3-0.6B-Base.pth",
        "Qwen-Qwen3-0.6B.pth",
        "Qwen-Qwen3-14B-Base.pth",
        "Qwen-Qwen3-14B.pth",
        "Qwen-Qwen3-1.7B-Base.pth",
        "Qwen-Qwen3-1.7B.pth",
        "Qwen-Qwen3-32B.pth",
        "Qwen-Qwen3-4B-Base.pth",
        "Qwen-Qwen3-4B.pth",
        "Qwen-Qwen3-8B-Base.pth",
        "Qwen-Qwen3-8B.pth",
        "Qwen-Qwen3-VL-2B-Instruct.pth",
        "Qwen-Qwen3-VL-2B-Thinking.pth",
        "Qwen-Qwen3-VL-32B-Instruct.pth",
        "Qwen-Qwen3-VL-32B-Thinking.pth",
        "Qwen-Qwen3-VL-4B-Instruct.pth",
        "Qwen-Qwen3-VL-4B-Thinking.pth",
        "Qwen-Qwen3-VL-8B-Instruct.pth",
        "Qwen-Qwen3-VL-8B-Thinking.pth",
        "Qwen-Qwen3.5-0.8B-Base.pth",
        "Qwen-Qwen3.5-0.8B.pth",
        "Qwen-Qwen3.5-27B.pth",
        "Qwen-Qwen3.5-2B-Base.pth",
        "Qwen-Qwen3.5-2B.pth",
        "Qwen-Qwen3.5-4B-Base.pth",
        "Qwen-Qwen3.5-4B.pth",
        "Qwen-Qwen3.5-9B-Base.pth",
        "Qwen-Qwen3.5-9B.pth",
        "unsloth-Llama-3.2-11B-Vision.pth",
        "unsloth-Llama-3.2-90B-Vision.pth",
    ]

    data_acc_models = [
        "allenai-Olmo-3-1025-7B.pth",
        "allenai-Olmo-3-1125-32B.pth",
        "allenai-Olmo-3.1-32B-Instruct.pth",
        "allenai-Olmo-3.1-32B-Think.pth",
        "allenai-Olmo-3-7B-Instruct.pth",
        "allenai-Olmo-3-7B-Think.pth",
        "deepseek-ai-DeepSeek-R1-Distill-Llama-70B.pth",
        "deepseek-ai-DeepSeek-R1-Distill-Llama-8B.pth",
        "deepseek-ai-DeepSeek-R1-Distill-Qwen-14B.pth",
        "deepseek-ai-DeepSeek-R1-Distill-Qwen-1.5B.pth",
        "deepseek-ai-DeepSeek-R1-Distill-Qwen-32B.pth",
        "deepseek-ai-DeepSeek-R1-Distill-Qwen-7B.pth",
        "meta-llama-Llama-3.1-70B-Instruct.pth",
        "meta-llama-Llama-3.1-70B.pth",
        "meta-llama-Llama-3.1-8B-Instruct.pth",
        "meta-llama-Llama-3.1-8B.pth",
        "meta-llama-Llama-3.2-1B-Instruct.pth",
        "meta-llama-Llama-3.2-1B.pth",
        "meta-llama-Llama-3.2-3B-Instruct.pth",
        "meta-llama-Llama-3.2-3B.pth",
        "meta-llama-Meta-Llama-3-8B-Instruct.pth",
        "meta-llama-Meta-Llama-3-8B.pth",
        "Qwen-Qwen1.5-0.5B-Chat.pth",
        "Qwen-Qwen1.5-0.5B.pth",
        "Qwen-Qwen1.5-14B-Chat.pth",
        "Qwen-Qwen1.5-14B.pth",
        "Qwen-Qwen1.5-1.8B-Chat.pth",
        "Qwen-Qwen1.5-1.8B.pth",
        "Qwen-Qwen1.5-32B-Chat.pth",
        "Qwen-Qwen1.5-32B.pth",
        "Qwen-Qwen1.5-4B-Chat.pth",
        "Qwen-Qwen1.5-4B.pth",
        "Qwen-Qwen1.5-72B-Chat.pth",
        "Qwen-Qwen1.5-72B.pth",
        "Qwen-Qwen1.5-7B-Chat.pth",
        "Qwen-Qwen1.5-7B.pth",
        "Qwen-Qwen2-0.5B-Instruct.pth",
        "Qwen-Qwen2-0.5B.pth",
        "Qwen-Qwen2-1.5B-Instruct.pth",
        "Qwen-Qwen2-1.5B.pth",
        "Qwen-Qwen2-72B-Instruct.pth",
        "Qwen-Qwen2-72B.pth",
        "Qwen-Qwen2-7B-Instruct.pth",
        "Qwen-Qwen2-7B.pth",
        "Qwen-Qwen2.5-0.5B-Instruct.pth",
        "Qwen-Qwen2.5-0.5B.pth",
        "Qwen-Qwen2.5-14B-Instruct.pth",
        "Qwen-Qwen2.5-14B.pth",
        "Qwen-Qwen2.5-1.5B-Instruct.pth",
        "Qwen-Qwen2.5-1.5B.pth",
        "Qwen-Qwen2.5-32B-Instruct.pth",
        "Qwen-Qwen2.5-32B.pth",
        "Qwen-Qwen2.5-3B-Instruct.pth",
        "Qwen-Qwen2.5-3B.pth",
        "Qwen-Qwen2.5-72B-Instruct.pth",
        "Qwen-Qwen2.5-72B.pth",
        "Qwen-Qwen2.5-7B-Instruct.pth",
        "Qwen-Qwen2.5-7B.pth",
        "Qwen-Qwen2.5-Coder-0.5B.pth",
        "Qwen-Qwen2.5-Coder-14B.pth",
        "Qwen-Qwen2.5-Coder-1.5B.pth",
        "Qwen-Qwen2.5-Coder-32B.pth",
        "Qwen-Qwen2.5-Coder-3B.pth",
        "Qwen-Qwen2.5-Coder-7B.pth",
        "Qwen-Qwen2.5-Math-1.5B.pth",
        "Qwen-Qwen2.5-Math-72B.pth",
        "Qwen-Qwen2.5-Math-7B.pth",
        "Qwen-Qwen3-0.6B-Base.pth",
        "Qwen-Qwen3-0.6B.pth",
        "Qwen-Qwen3-14B-Base.pth",
        "Qwen-Qwen3-14B.pth",
        "Qwen-Qwen3-1.7B-Base.pth",
        "Qwen-Qwen3-1.7B.pth",
        "Qwen-Qwen3-32B.pth",
        "Qwen-Qwen3-4B-Base.pth",
        "Qwen-Qwen3-4B.pth",
        "Qwen-Qwen3-8B-Base.pth",
        "Qwen-Qwen3-8B.pth",
        "Qwen-Qwen3.5-0.8B-Base.pth",
        "Qwen-Qwen3.5-0.8B.pth",
        "Qwen-Qwen3.5-27B.pth",
        "Qwen-Qwen3.5-2B-Base.pth",
        "Qwen-Qwen3.5-2B.pth",
        "Qwen-Qwen3.5-4B.pth",
        "Qwen-Qwen3.5-9B-Base.pth",
        "Qwen-Qwen3.5-9B.pth",
    ]

    data_meta_models = data_acc_models

    data_instruct_models = [
        "allenai-Olmo-3.1-32B-Instruct.pth",
        "allenai-Olmo-3-7B-Instruct.pth",
        "meta-llama-Llama-3.1-70B-Instruct.pth",
        "meta-llama-Llama-3.1-8B-Instruct.pth",
        "meta-llama-Llama-3.2-1B-Instruct.pth",
        "meta-llama-Llama-3.2-3B-Instruct.pth",
        "meta-llama-Meta-Llama-3-8B-Instruct.pth",
        "Qwen-Qwen1.5-0.5B-Chat.pth",
        "Qwen-Qwen1.5-14B-Chat.pth",
        "Qwen-Qwen1.5-1.8B-Chat.pth",
        "Qwen-Qwen1.5-32B-Chat.pth",
        "Qwen-Qwen1.5-4B-Chat.pth",
        "Qwen-Qwen1.5-72B-Chat.pth",
        "Qwen-Qwen1.5-7B-Chat.pth",
        "Qwen-Qwen2-0.5B-Instruct.pth",
        "Qwen-Qwen2-1.5B-Instruct.pth",
        "Qwen-Qwen2-72B-Instruct.pth",
        "Qwen-Qwen2-7B-Instruct.pth",
        "Qwen-Qwen2.5-0.5B-Instruct.pth",
        "Qwen-Qwen2.5-14B-Instruct.pth",
        "Qwen-Qwen2.5-1.5B-Instruct.pth",
        "Qwen-Qwen2.5-32B-Instruct.pth",
        "Qwen-Qwen2.5-3B-Instruct.pth",
        "Qwen-Qwen2.5-72B-Instruct.pth",
        "Qwen-Qwen2.5-7B-Instruct.pth",
        "Qwen-Qwen3-0.6B.pth",
        "Qwen-Qwen3-14B.pth",
        "Qwen-Qwen3-1.7B.pth",
        "Qwen-Qwen3-32B.pth",
        "Qwen-Qwen3-4B.pth",
        "Qwen-Qwen3-8B.pth",
        "Qwen-Qwen3.5-0.8B.pth",
        "Qwen-Qwen3.5-27B.pth",
        "Qwen-Qwen3.5-2B.pth",
        "Qwen-Qwen3.5-4B.pth",
        "Qwen-Qwen3.5-9B.pth",
    ]

    configs = [
        ("data",         data_models,         "full_data_jureca_data.csv"),
        ("data_acc",     data_acc_models,      "full_data_jureca_data_acc.csv"),
        ("data_meta",    data_meta_models,     "full_data_jureca_data_meta.csv"),
        ("data_instruct", data_instruct_models, "full_data_jureca_data_instruct.csv"),
    ]

    experiments = glob('../data/*')

    for base_dir, models, out_file in configs:
        data = []
        for experiment in experiments:
            print(experiment)
            exp_name = os.path.basename(experiment)
            for fname in models:
                path = os.path.join('..', base_dir, exp_name, fname)
                try:
                    nlls = torch.load(path, map_location="cpu")
                    for participant, values in nlls.items():
                        for trial, nll in enumerate(values.tolist()):
                            data.append([base_dir, experiment, fname, participant, trial, nll])
                except:
                    print("Not found", base_dir, experiment, fname)
            print()

        df = pd.DataFrame(data, columns=['directory', 'experiment', 'model', 'participant', 'trial', 'nll'])
        print(df)
        print(df.groupby(['directory', 'model'])['nll'].mean())
        df.to_csv(out_file, index=False)
